#!/bin/bash

ROOT="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"

source ${ROOT}/noelle/enable


LLVM_ENABLE=${ALASKA}/llvm/9.0.1/enable
[ -f ${LLVM_ENABLE} ] && source ${LLVM_ENABLE}
